services:
  trivujpad:
    build: .
    container_name: trivujpad
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: '0.50'
        reservations:
          memory: 50M

    networks:
      - minhazul-net

networks:
  minhazul-net:
    external: true
