name: Build Docker Image
run-name: ${{ github.actor }} is Building with docker
on:
  push:
    tags:
      - "*" # Push events to every tag not containing /

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: minhaz1217/minhaz1217
          tags: |
            type=semver,event=push tag,pattern={{major}}.{{minor}}.{{patch}},prefix=trivujpad-
            type=raw,enable=true,priority=200,prefix=trivujpad-,value=latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the image
        uses: docker/build-push-action@v6
        id: docker-build-push
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Name of the image
        run: |
          echo ${{steps.docker-build-push.outputs.manifest:org.opencontainers.image.version }}
          echo Next
          echo ${{ steps.docker-build-push.outputs }}
