name: Build Docker Image
run-name: ${{ github.actor }} is Building with docker
on:
  push:
    tags:        
      - '*'   # Push events to every tag not containing /

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: name/app
          tags: |
            type=semver,event=push tag,pattern={{major}}.{{minor}}.{{patch}}

      - name: Build the image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
