name: Build Docker Image
run-name: ${{ github.actor }} is Building with docker
on:
  push:
    branches: [master]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: debug
        run: git describe --tags `git rev-list --tags --max-count=1`
      - name: Get Previous Version
        id: get-previous-version
        run: bash ./.github/workflows/scripts/previous-version.sh
      
      - name: Generate Next Version
        id: get-next-version
        run: bash ./.github/workflows/scripts/next-version.sh -p ${{steps.get-previous-version.outputs.PREVIOUS_VERSION}}
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: minhaz1217/minhaz1217
          tags: |
            type=raw,enable=true,priority=200,prefix=trivujpad-,value=${{steps.get-next-version.outputs.NEXT_VERSION}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the image
        uses: docker/build-push-action@v6
        id: docker-build-push
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Name of the image
        run: |
          echo Image name ${{ fromJSON(steps.docker-build-push.outputs.metadata)['image.name'] }}
          echo Next 1
          echo ${{steps.docker-build-push.outputs.manifest.org.opencontainers.image.version }}
          echo Next 2
          echo ${{ steps.docker-build-push.outputs }}
